/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UoaHelp {
        /**
          * Html Content of the modal. It can be passed as a property/attribute or as html content inside uoa-help tag.
         */
        "htmlContent"?: string;
        /**
          * Clickable text of Link
         */
        "linkText": string;
        /**
          * Title of the modal
         */
        "modalTitle": string;
    }
}
declare global {
    interface HTMLUoaHelpElement extends Components.UoaHelp, HTMLStencilElement {
    }
    var HTMLUoaHelpElement: {
        prototype: HTMLUoaHelpElement;
        new (): HTMLUoaHelpElement;
    };
    interface HTMLElementTagNameMap {
        "uoa-help": HTMLUoaHelpElement;
    }
}
declare namespace LocalJSX {
    interface UoaHelp {
        /**
          * Html Content of the modal. It can be passed as a property/attribute or as html content inside uoa-help tag.
         */
        "htmlContent"?: string;
        /**
          * Clickable text of Link
         */
        "linkText"?: string;
        /**
          * Title of the modal
         */
        "modalTitle"?: string;
    }
    interface IntrinsicElements {
        "uoa-help": UoaHelp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uoa-help": LocalJSX.UoaHelp & JSXBase.HTMLAttributes<HTMLUoaHelpElement>;
        }
    }
}
